DELETE FROM public.mega_menu_items;

ALTER TABLE public.mega_menu_items DROP CONSTRAINT IF EXISTS mega_menu_items_section_check;
ALTER TABLE public.mega_menu_items ADD CONSTRAINT mega_menu_items_section_check CHECK (section = ANY (ARRAY['tops','outerwear','bottoms','workwear','headwear','bags','drinkware','promo','manufacturers']));

INSERT INTO public.mega_menu_items (section, label_lv, label_en, categories, sort_order, active, auto_added) VALUES
('tops','T-krekli un topi','T-shirts & tops',ARRAY['T-shirts','Tops','Tees'],10,true,false),
('tops','Polo krekli','Polos',ARRAY['Polos','Polo shirts'],20,true,false),
('tops','Krekli','Shirts',ARRAY['Shirts'],30,true,false),
('tops','Hūdiji','Hoodies',ARRAY['Hoodies','Hoodie sweatshirts'],40,true,false),
('tops','Džemperi un flīsi','Sweatshirts & fleece',ARRAY['Sweaters','Sweatshirts','Crew neck sweatshirts','Fleece'],50,true,false),
('outerwear','Virsjakas','Jackets',ARRAY['Jackets','Non Padded Jacket','Jackets-Vests'],10,true,false),
('outerwear','Vestes','Bodywarmers',ARRAY['Bodywarmers','Vests'],20,true,false),
('outerwear','Atstarojošais apģērbs','Hi-vis clothing',ARRAY['Safety','Safety Vests','Hi-vis'],30,true,false),
('bottoms','Bikses','Trousers',ARRAY['Bottoms','Trousers-shorts','Trousers'],10,true,false),
('bottoms','Šorti','Shorts',ARRAY['Shorts','Shorts & Trousers'],20,true,false),
('bottoms','Sporta apģērbs','Sportswear',ARRAY['Sportswear','Sports','Fitness & Sport','Training Set','Training pants'],30,true,false),
('bottoms','Zeķes','Socks',ARRAY['Socks'],40,true,false),
('workwear','Darba apģērbs','Workwear',ARRAY['Workwear','Coveralls'],10,true,false),
('workwear','Darba apavi','Safety footwear',ARRAY['Shoes','Safety Footwear'],20,true,false),
('workwear','Cimdi','Gloves',ARRAY['Gloves'],30,true,false),
('workwear','Priekšauti','Aprons',ARRAY['Aprons'],40,true,false),
('headwear','Cepures','Caps & beanies',ARRAY['Caps & Hats','Caps','Headwear','Beanies'],10,true,false),
('headwear','Šalles','Scarves',ARRAY['Scarves'],20,true,false),
('headwear','Dvieļi','Towels',ARRAY['Towels','Terry'],30,true,false),
('headwear','Pledi','Blankets',ARRAY['Blankets','Fleece Blankets'],40,true,false),
('bags','Auduma somas','Tote bags',ARRAY['Tote Bags','Shopping & Tote Bags','Drawstring Bags'],10,true,false),
('bags','Mugursomas','Backpacks',ARRAY['Backpacks','Laptop Backpacks'],20,true,false),
('bags','Datoru somas','Laptop bags',ARRAY['Laptop & Tablet Bags'],30,true,false),
('bags','Biznesa somas','Business bags',ARRAY['Business Bags','Portfolios','Conference Bags'],40,true,false),
('bags','Sporta somas','Sports bags',ARRAY['Sports Bags','Travel Bags','Trolleys & Suitcases'],50,true,false),
('bags','Jostas somas','Waist bags',ARRAY['Waist Bags','Belt Bags'],60,true,false),
('bags','Aukstumsomas','Cooler bags',ARRAY['Cooler Bags'],70,true,false),
('drinkware','Pudeles un termosi','Bottles',ARRAY['Bottles','Water Bottles','Sports Bottles','Insulated Bottles'],10,true,false),
('drinkware','Krūzes','Mugs',ARRAY['Mugs','Standard Mugs','Insulated Mugs','Travel Mugs'],20,true,false),
('drinkware','Glāzes un vīna aksesuāri','Glasses & wine',ARRAY['Glasses','Bar glass','Carafes','Wine Accessories','Bottle Openers & Accessories'],30,true,false),
('promo','Bloknoti un pildspalvas','Notebooks & pens',ARRAY['Hard Cover Notebooks','Soft Cover Notebooks','Notepads','Ballpoint Pens','Rollerball Pens','Pencils'],10,true,false),
('promo','Austiņas un skaļruņi','Audio',ARRAY['Speakers','Earbuds','Headphones'],20,true,false),
('promo','Lādētāji un USB','Chargers & USB',ARRAY['Power Banks','Wireless Charging','Chargers','Cables','USB Flash Drives','USB Hubs'],30,true,false),
('promo','Lietussargi','Umbrellas',ARRAY['Standard Umbrellas','Folding Umbrellas','Golf Umbrellas','Storm Umbrellas'],40,true,false),
('promo','Dāvanu komplekti','Gift sets',ARRAY['Gift Sets'],50,true,false),
('promo','Biroja piederumi','Office accessories',ARRAY['Office','Desk Accessories','Office Stands & Holders','Sticky Notes'],60,true,false),
('manufacturers','Stanley/Stella','Stanley/Stella',ARRAY['stanley-stella'],10,true,false),
('manufacturers','Craft','Craft',ARRAY['nwg-craft'],20,true,false),
('manufacturers','Clique','Clique',ARRAY['nwg-clique'],30,true,false),
('manufacturers','ProJob','ProJob',ARRAY['nwg-projob'],40,true,false),
('manufacturers','Cutter & Buck','Cutter & Buck',ARRAY['nwg-cutter'],50,true,false),
('manufacturers','Elevate','Elevate',ARRAY['pf-elevate'],60,true,false),
('manufacturers','Roly','Roly',ARRAY['pf-roly'],70,true,false),
('manufacturers','Russell','Russell',ARRAY['ru'],80,true,false),
('manufacturers','Beechfield Brands','Beechfield Brands',ARRAY['bb'],90,true,false),
('manufacturers','Malfini','Malfini',ARRAY['mf'],100,true,false),
('manufacturers','Prezentmateriāli','Promotional products',ARRAY['pf'],110,true,false);